baseURL: "http://example.org/"
languageCode: en-us
title: Welcome to FlightDeck-Go

# SEO Privacy
googleAnalytics: UX-xxxxxx-xx
enableRobotsTXT: true

disableRSS: true
disableKinds: ["section", "taxonomy", "taxonomyTerm", "RSS"]

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
